# Generated by Django 5.1 on 2026-06-16 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='scheduled',
            new_name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ga',
        ),
        migrations.RemoveField(
            model_name='team',
            name='gf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='played',
        ),
        migrations.RemoveField(
            model_name='team',
            name='status',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='season',
        ),
        migrations.AddField(
            model_name='team',
            name='goals_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.group'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='owner_password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='team',
            name='owner_username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.tournament'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='competition.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='competition.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('group', 'Phase de groupes'), ('R16', 'Huitièmes'), ('QF', 'Quarts'), ('SF', 'Demi'), ('F', 'Finale')], default='group', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.tournament'),
        ),
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.tournament'),
        ),
        migrations.AlterField(
            model_name='team',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Goma Efootball Championship', max_length=100),
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
    ]
