# Generated by Django 5.1 on 2026-06-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_rename_scheduled_match_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('group', 'Poules'), ('R16', 'Huitièmes de finale'), ('QF', 'Quarts de finale'), ('SF', 'Demi-finales'), ('3P', 'Match 3ème place'), ('F', 'Finale')], default='group', max_length=10),
        ),
    ]
