# Generated by Django 5.1 on 2026-06-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_match_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='collective_strength',
            field=models.IntegerField(blank=True, default=0, help_text='Force collective eFootball (ex: 3209)'),
        ),
    ]
