# Generated by Django 5.1 on 2026-06-29 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_team_collective_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_goals_et',
            field=models.IntegerField(blank=True, help_text='Buts extérieur en prolongation', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='away_penalties',
            field=models.IntegerField(blank=True, help_text='Tirs au but extérieur', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='extra_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='home_goals_et',
            field=models.IntegerField(blank=True, help_text='Buts domicile en prolongation', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_penalties',
            field=models.IntegerField(blank=True, help_text='Tirs au but domicile', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalty_shootout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='competition.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='competition.team'),
        ),
    ]
